# Generated by Django 3.1.4 on 2020-12-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='paid_file',
        ),
    ]
